[package]
name = "slint_init"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
debug = false
opt-level = 3
strip = "symbols"
lto = "fat"
panic = "abort"
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1